jobs:
  run-app:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cdrx/pyqt5:latest  # Qt + Python preinstalled

    steps:
    - uses: actions/checkout@v3

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run app.py
      run: xvfb-run --auto-servernum -- python app.py
