name: QtInterface CI

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'qtinterface.py'
      - 'test_qtinterface*.py'
      - 'requirements.txt'
      - '.github/workflows/qtinterface-ci.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'qtinterface.py'
      - 'test_qtinterface*.py'
      - 'requirements.txt'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xkb1 libxkbcommon-x11-0
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov pytest-qt flake8
        pip install -r requirements.txt
        
    # - name: Lint with flake8
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 qtinterface.py --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings
    #     flake8 qtinterface.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Test with pytest on Linux
      if: runner.os == 'Linux'
      run: |
        xvfb-run --auto-servernum pytest test_qtinterface*.py -v --cov=qtinterface
        
    - name: Test with pytest on Windows/macOS
      if: runner.os != 'Linux'
      run: |
        pytest test_qtinterface*.py -v --cov=qtinterface
        
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: qtinterface
        name: codecov-qtinterface

  build:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.10']
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --name=qtinterface --windowed --onefile qtinterface.py
        
    # - name: Upload build artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: qtinterface-${{ runner.os }}
    #     path: dist/